###Cadastrar 
POST https://localhost:5001/api/carro/create 
Content-Type: application/json

{
    "Marca" : "gol",
    "Valor" : 60.000,
    "buyId": 1
}


###Listar
GET https://localhost:5001/api/carro/list 

###Buscar pela ID
GET https://localhost:5001/api/carro/getbyid/3


###Deletar pela marca
GET https://localhost:5001/api/carro/delete/monza

###Editar carro
PUT https://localhost:5001/api/carro/update 
Content-Type: application/json

{
    "Id": 3,
    "Marca": "astra",
    "Valor": 50.000,
    "buyId": 4
}