###Cadastrar 
POST https://localhost:5001/api/carro/create 
Content-Type: application/json

{
    "Marca" : "uno",
    "Valor" : 90.000,
    "Usuario": { 
        
    },
    "UserId": 1
}

###Listar
GET https://localhost:5001/api/carro/list 

###Buscar pela ID
GET https://localhost:5001/api/carro/getbyid/2

###Deletar pelo id
DELETE https://localhost:5001/api/carro/delete/3

###Editar carro
PUT https://localhost:5001/api/carro/update 
Content-Type: application/json

{
    "Id":2,
    "Marca" : "fitat",
    "Valor" : 50.000,
    "Usuario": { 
        "Id" : 2,
        "Nome": "fernanda ",
        "Email": "feer@"
    },
    "UserId": 1
    
}